version: "3.7"
services:

    apromore:
        image: apromore/apromore:7.12
        container_name: apromore
        depends_on:
            - apromoresql
        ports:
            - "80:9000"

    apromoresql:
        image: mysql:5.7
        container_name: apromoresql
        command: --max_allowed_packet=2G
        environment:
            MYSQL_ROOT_PASSWORD: MAcri
            MYSQL_DATABASE: apromore
            MYSQL_USER: apromore
            MYSQL_PASSWORD: MAcri
        volumes:
            - "./mysql-data:/var/lib/mysql"
        expose:
            - "3306"          