version: "3.7"
services:

    apromore:
        image: apromore/apromore:7.12
        container_name: apromore
        volumes:
            - "./apromore/Editor-Repository:/opt/apromore/Editor-Repository"
            - "./apromore/Event-Logs-Repository:/opt/apromore/Event-Logs-Repository"
            - "./apromore/Filestore-Repository:/opt/apromore/Filestore-Repository"
            - "./apromore/Lucene-Repository:/opt/apromore/Lucene-Repository"
        depends_on:
            - apromoresql
        ports:
            - "9000:9000"

    apromoresql:
        image: mysql:5.7
        container_name: apromoresql
        command: --max_allowed_packet=2G
        environment:
            MYSQL_ROOT_PASSWORD: MAcri
            MYSQL_DATABASE: apromore
            MYSQL_USER: apromore
            MYSQL_PASSWORD: MAcri
        volumes:
            - "./apromore/mysql-data:/var/lib/mysql"
        expose:
            - "3306"          